# ----------------------------
# Set NAME to the program name
# Set ICON to the png icon file name
# Set DESCRIPTION to display within a compatible shell
# Set COMPRESSED to "YES" to create a compressed program
# ----------------------------

NAME        ?= TORSEUR
COMPRESSED  ?= YES
ICON        ?= iconc.png
DESCRIPTION ?= "M4x1m3's Torseurs solver"

# ----------------------------

include $(CEDEV)/include/.makefile
